### ISSUE TITLE
1.0.12 Issues

### ISSUE THREAD

**Issue by madbuda** [MyHush/hush#46]
List of known issues / TODOs for 1.0.12

- [ ] Arch build
- [ ] hush-tx (need address indexing for qa)
- [ ] branding (this needs to be expanded)
- [x] Windows build https://github.com/madbuda/hush/releases/tag/v1.0.12
- [ ] Mac build
- [x] update apt repo https://github.com/MyHush/hush/issues/57
- [ ] run help2man on hush-cli, hushd, hush-tx to generate new man page files
- [x] https://github.com/MyHush/hush/issues/34 Adjust auto-senescence parameters
- [x] https://github.com/MyHush/hush/pull/52 Testnet
- [x] Swing wallet update with new bins https://github.com/vaklinov/hush-swing-wallet-ui/issues/13

**Comment by leto** [comment]
@madbuda can you explain a bit more about what is needed with `hush-tx` ?

**Comment by madbuda** [comment]
basically we need to add address indexing into hushd see the old zdash bitcore repo https://github.com/MW-hush/zdash/tree/v1.0.4-bitcore

This is required for the bitcore libs and explorer to work with the new 1.0.12

**Comment by leto** [comment]
@madbuda nobody has any idea what `hush-tx (need address indexing for qa)` means, even with your latest comment. Please teach us to fish

**Comment by madbuda** [comment]
That statement doesn't inspire much confidence, I'm assuming you, not the dev team when I read that.

Address indexing is needed for bitcore, the component that is used to run our block explorers. Basically we need to add some bitcoin core features in that Zcash removes

**Comment by csharpee** [comment]
So for a quick update from what I know so far is from madbuda, 

https://github.com/str4d/zcash/tree/v1.0.11-rc1-bitcore
looks like zcash ony has 1.0.11 rc as their latest bitcore implimentation. I'll reach out to str4d and see if he's working on 1.0.12 or if there aren't any major changes needed for it.

**Comment by csharpee** [comment]
Which files do we need re-branding for? Do we want to rename all files/folders?

**Comment by madbuda** [comment]
To start look at the current dev branch, from there you could start digging through the code and rename / test

**Comment by csharpee** [comment]
Okay, new updates for branding, help2man, auto-senescence and hush-tx.  #49 #56

**Comment by madbuda** [comment]
I maintain an apt repository for hush, will need to build new deb and test, then update apt repo

**Comment by leto** [comment]
@madbuda @csharpee I created https://github.com/MyHush/hush/issues/57 to track building the 1.0.12 deb, let's try to keep this issue well documented and closable

**Comment by madbuda** [comment]
I closed it, there is a checkbox in this issue already for deb builds and apt updates

**Comment by madbuda** [comment]
@leto this is already documented in our repo

**Comment by LucyDemooon** [comment]
possible to update gcc to version 6 or 7 instead of 5?
have no gcc verison 5 anymore in the repos (Manjaro/Arch Linux)
