### ISSUE TITLE
New official Hush testnet #bounty

### ISSUE THREAD

**Issue by leto** [MyHush/hush#6]
### Describe the issue

We do not have a testnet for core devs to develop new features on and use as a testing ground.

### Bounty

This is worth 500 Hush

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:
1. Observe
2. No
3. Testnet

### Expected behaviour

A testnet should exist.

### Actual behaviour + errors

To close this issue, we must have a new Genesis block created and mined. Then, the IP of the origin testnet node needs to be added to the code and then other nodes can begin to connect to the testnet.

This issue is only for getting the origin node up and running and the genesis block created and mined.

### ToDo

- [x] Generate new Hush genesis block
- [x] Mine new genesis block
- [x] Update testnet code with IP of new origin testnet node

### The version of Hush you were using:
All

**Comment by Scottrock** [comment]
Change the currency units from TAZ to an appropriate unit for Hush testnet (please not Tush)

**Comment by leto** [comment]
This is related: https://github.com/MyHush/hush/pull/17

**Comment by radix42** [comment]
I am so very sorry but I am making a condition of collecting this bounty that the testnet units be TUSH
oh and let's give it the nice fresh name testnet4, as all the testnet3 attempts and stuff people have lying around crippled on HD's are useless right now anyway.

**Comment by madbuda** [comment]
@radix42 t1c11VazKq24xJoM55Cp4rpxeM4p6xxmcuR is @mrhcbojangles for https://github.com/MyHush/hush/pull/37

**Comment by radix42** [comment]
Waiting for confirmations, but paid!
https://explorer.myhush.org/tx/a7afe4f618ab8ffa6327f6626c8e828fbfe71d360d2fc8e5779da02b426cef04

**Comment by mrhcbojangles** [comment]
Thanks!
